using System;
using UnityEditor;
using UnityEngine;

namespace Shiroi.Unity.Pathfinding2D.Editor {
    public static class GUIStyles {
        public static GUIStyle Get(string key, EditorSkin skin = EditorSkin.Inspector) {
            return EditorGUIUtility.GetBuiltinSkin(skin).FindStyle(key);
        }

        public const string box = "box";
        public const string button = "button";
        public const string toggle = "toggle";
        public const string label = "label";
        public const string window = "window";
        public const string textfield = "textfield";
        public const string textarea = "textarea";
        public const string horizontalslider = "horizontalslider";
        public const string horizontalsliderthumb = "horizontalsliderthumb";
        public const string verticalslider = "verticalslider";
        public const string verticalsliderthumb = "verticalsliderthumb";
        public const string horizontalscrollbar = "horizontalscrollbar";
        public const string horizontalscrollbarthumb = "horizontalscrollbarthumb";
        public const string horizontalscrollbarleftbutton = "horizontalscrollbarleftbutton";
        public const string horizontalscrollbarrightbutton = "horizontalscrollbarrightbutton";
        public const string verticalscrollbar = "verticalscrollbar";
        public const string verticalscrollbarthumb = "verticalscrollbarthumb";
        public const string verticalscrollbarupbutton = "verticalscrollbarupbutton";
        public const string verticalscrollbardownbutton = "verticalscrollbardownbutton";
        public const string scrollview = "scrollview";
        public const string AboutWIndowLicenseLabel = "AboutWIndowLicenseLabel";
        public const string ACButton = "AC Button";
        public const string ACLeftArrow = "AC LeftArrow";
        public const string ACRightArrow = "AC RightArrow";
        public const string AnimationEventBackground = "AnimationEventBackground";
        public const string AnimationEventTooltip = "AnimationEventTooltip";
        public const string AnimationEventTooltipArrow = "AnimationEventTooltipArrow";
        public const string AnimationKeyframeBackground = "AnimationKeyframeBackground";
        public const string AnimationPlayHead = "AnimationPlayHead";
        public const string AnimationRowEven = "AnimationRowEven";
        public const string AnimationRowOdd = "AnimationRowOdd";
        public const string AnimationSelectionTextField = "AnimationSelectionTextField";
        public const string AnimationSequencerLinkButton = "AnimationSequencerLinkButton";
        public const string AnimationTimelineTick = "AnimationTimelineTick";
        public const string AnimPropDropdown = "AnimPropDropdown";
        public const string AppToolbar = "AppToolbar";
        public const string AssetLabel = "AssetLabel";
        public const string AssetLabelIcon = "AssetLabel Icon";
        public const string AssetLabelPartial = "AssetLabel Partial";
        public const string AudioKnobOverlay = "AudioKnobOverlay";
        public const string BoldLabel = "BoldLabel";
        public const string BoldToggle = "BoldToggle";
        public const string ButtonLeft = "ButtonLeft";
        public const string ButtonMid = "ButtonMid";
        public const string ButtonRight = "ButtonRight";
        public const string BypassToggle = "BypassToggle";
        public const string CapsuleButton = "CapsuleButton";
        public const string ChannelStripAttenuationBar = "ChannelStripAttenuationBar";
        public const string ChannelStripAttenuationMarkerSquare = "ChannelStripAttenuationMarkerSquare";
        public const string ChannelStripBg = "ChannelStripBg";
        public const string ChannelStripDuckingMarker = "ChannelStripDuckingMarker";
        public const string ChannelStripEffectBar = "ChannelStripEffectBar";
        public const string ChannelStripSendReturnBar = "ChannelStripSendReturnBar";
        public const string ChannelStripVUMeterBg = "ChannelStripVUMeterBg";
        public const string CircularToggle = "CircularToggle";
        public const string CNBox = "CN Box";
        public const string CNCountBadge = "CN CountBadge";
        public const string CNEntryBackEven = "CN EntryBackEven";
        public const string CNEntryBackOdd = "CN EntryBackOdd";
        public const string CNEntryError = "CN EntryError";
        public const string CNEntryErrorIcon = "CN EntryErrorIcon";
        public const string CNEntryErrorIconSmall = "CN EntryErrorIconSmall";
        public const string CNEntryErrorSmall = "CN EntryErrorSmall";
        public const string CNEntryInfo = "CN EntryInfo";
        public const string CNEntryInfoIcon = "CN EntryInfoIcon";
        public const string CNEntryInfoIconSmall = "CN EntryInfoIconSmall";
        public const string CNEntryInfoSmall = "CN EntryInfoSmall";
        public const string CNEntryWarn = "CN EntryWarn";
        public const string CNEntryWarnIcon = "CN EntryWarnIcon";
        public const string CNEntryWarnIconSmall = "CN EntryWarnIconSmall";
        public const string CNEntryWarnSmall = "CN EntryWarnSmall";
        public const string CNMessage = "CN Message";
        public const string CNStatusError = "CN StatusError";
        public const string CNStatusInfo = "CN StatusInfo";
        public const string CNStatusWarn = "CN StatusWarn";
        public const string ColorField = "ColorField";
        public const string ColorPicker2DThumb = "ColorPicker2DThumb";
        public const string ColorPickerBackground = "ColorPickerBackground";
        public const string ColorPickerBox = "ColorPickerBox";
        public const string ColorPickerCurrentColor = "ColorPickerCurrentColor";
        public const string ColorPickerCurrentExposureSwatchBorder = "ColorPickerCurrentExposureSwatchBorder";
        public const string ColorPickerExposureSwatch = "ColorPickerExposureSwatch";
        public const string ColorPickerHorizThumb = "ColorPickerHorizThumb";
        public const string ColorPickerHueRing = "ColorPickerHueRing";
        public const string ColorPickerHueRingThumb = "ColorPickerHueRingThumb";
        public const string ColorPickerOriginalColor = "ColorPickerOriginalColor";
        public const string ColorPickerSliderBackground = "ColorPickerSliderBackground";
        public const string ColorPickerVertThumb = "ColorPickerVertThumb";
        public const string Command = "Command";
        public const string CommandLeft = "CommandLeft";
        public const string CommandMid = "CommandMid";
        public const string CommandRight = "CommandRight";
        public const string ControlHighlight = "ControlHighlight";
        public const string ControlLabel = "ControlLabel";
        public const string CurveEditorBackground = "CurveEditorBackground";
        public const string CurveEditorLabelTickmarks = "CurveEditorLabelTickmarks";
        public const string debug_layout_box = "debug_layout_box";
        public const string dockarea = "dockarea";
        public const string dockareaOverlay = "dockareaOverlay";
        public const string dockareaStandalone = "dockareaStandalone";
        public const string DopesheetBackground = "DopesheetBackground";
        public const string Dopesheetkeyframe = "Dopesheetkeyframe";
        public const string DopesheetScaleLeft = "DopesheetScaleLeft";
        public const string DopesheetScaleRight = "DopesheetScaleRight";
        public const string dragtab = "dragtab";
        public const string dragtabdropwindow = "dragtabdropwindow";
        public const string DropDown = "DropDown";
        public const string DropDownButton = "DropDownButton";
        public const string EditModeToolbar = "EditModeToolbar";
        public const string EditModeToolbarLeft = "EditModeToolbarLeft";
        public const string EditModeToolbarMid = "EditModeToolbarMid";
        public const string EditModeToolbarRight = "EditModeToolbarRight";
        public const string ErrorLabel = "ErrorLabel";
        public const string ExposablePopupItem = "ExposablePopupItem";
        public const string ExposablePopupMenu = "ExposablePopupMenu";
        public const string EyeDropperHorizontalLine = "EyeDropperHorizontalLine";
        public const string EyeDropperPickedPixel = "EyeDropperPickedPixel";
        public const string EyeDropperVerticalLine = "EyeDropperVerticalLine";
        public const string flowbackground = "flow background";
        public const string flownavbarback = "flow navbar back";
        public const string flownavbarbutton = "flow navbar button";
        public const string flownavbarseparator = "flow navbar separator";
        public const string flownode0 = "flow node 0";
        public const string flownode0on = "flow node 0 on";
        public const string flownode1 = "flow node 1";
        public const string flownode1on = "flow node 1 on";
        public const string flownode2 = "flow node 2";
        public const string flownode2on = "flow node 2 on";
        public const string flownode3 = "flow node 3";
        public const string flownode3on = "flow node 3 on";
        public const string flownode4 = "flow node 4";
        public const string flownode4on = "flow node 4 on";
        public const string flownode5 = "flow node 5";
        public const string flownode5on = "flow node 5 on";
        public const string flownode6 = "flow node 6";
        public const string flownode6on = "flow node 6 on";
        public const string flownodehex0 = "flow node hex 0";
        public const string flownodehex0on = "flow node hex 0 on";
        public const string flownodehex1 = "flow node hex 1";
        public const string flownodehex1on = "flow node hex 1 on";
        public const string flownodehex2 = "flow node hex 2";
        public const string flownodehex2on = "flow node hex 2 on";
        public const string flownodehex3 = "flow node hex 3";
        public const string flownodehex3on = "flow node hex 3 on";
        public const string flownodehex4 = "flow node hex 4";
        public const string flownodehex4on = "flow node hex 4 on";
        public const string flownodehex5 = "flow node hex 5";
        public const string flownodehex5on = "flow node hex 5 on";
        public const string flownodehex6 = "flow node hex 6";
        public const string flownodehex6on = "flow node hex 6 on";
        public const string flownodetitlebar = "flow node titlebar";
        public const string flowoverlayarealeft = "flow overlay area left";
        public const string flowoverlayarearight = "flow overlay area right";
        public const string flowoverlaybox = "flow overlay box";
        public const string flowoverlayfoldout = "flow overlay foldout";
        public const string flowoverlayheaderlowerleft = "flow overlay header lower left";
        public const string flowoverlayheaderlowerright = "flow overlay header lower right";
        public const string flowoverlayheaderupperleft = "flow overlay header upper left";
        public const string flowoverlayheaderupperright = "flow overlay header upper right";
        public const string flowshaderin0 = "flow shader in 0";
        public const string flowshaderin1 = "flow shader in 1";
        public const string flowshaderin2 = "flow shader in 2";
        public const string flowshaderin3 = "flow shader in 3";
        public const string flowshaderin4 = "flow shader in 4";
        public const string flowshaderin5 = "flow shader in 5";
        public const string flowshadernode0 = "flow shader node 0";
        public const string flowshadernode0on = "flow shader node 0 on";
        public const string flowshaderout0 = "flow shader out 0";
        public const string flowshaderout1 = "flow shader out 1";
        public const string flowshaderout2 = "flow shader out 2";
        public const string flowshaderout3 = "flow shader out 3";
        public const string flowshaderout4 = "flow shader out 4";
        public const string flowshaderout5 = "flow shader out 5";
        public const string flowtargetin = "flow target in";
        public const string flowtriggerPinin = "flow triggerPin in";
        public const string flowtriggerPinout = "flow triggerPin out";
        public const string flowvar0 = "flow var 0";
        public const string flowvar0on = "flow var 0 on";
        public const string flowvar1 = "flow var 1";
        public const string flowvar1on = "flow var 1 on";
        public const string flowvar2 = "flow var 2";
        public const string flowvar2on = "flow var 2 on";
        public const string flowvar3 = "flow var 3";
        public const string flowvar3on = "flow var 3 on";
        public const string flowvar4 = "flow var 4";
        public const string flowvar4on = "flow var 4 on";
        public const string flowvar5 = "flow var 5";
        public const string flowvar5on = "flow var 5 on";
        public const string flowvar6 = "flow var 6";
        public const string flowvar6on = "flow var 6 on";
        public const string flowvarPinin = "flow varPin in";
        public const string flowvarPinout = "flow varPin out";
        public const string flowvarPintooltip = "flow varPin tooltip";
        public const string Foldout = "Foldout";
        public const string FoldOutPreDrop = "FoldOutPreDrop";
        public const string GameViewBackground = "GameViewBackground";
        public const string GradDownSwatch = "Grad Down Swatch";
        public const string GradDownSwatchOverlay = "Grad Down Swatch Overlay";
        public const string GradUpSwatch = "Grad Up Swatch";
        public const string GradUpSwatchOverlay = "Grad Up Swatch Overlay";
        public const string grey_border = "grey_border";
        public const string GridList = "GridList";
        public const string GridListText = "GridListText";
        public const string GridToggle = "GridToggle";
        public const string groupBackground = "groupBackground";
        public const string GroupBox = "GroupBox";
        public const string GVGizmoDropDown = "GV Gizmo DropDown";
        public const string HeaderLabel = "HeaderLabel";
        public const string HelpBox = "HelpBox";
        public const string HiLabel = "Hi Label";
        public const string HorizontalMinMaxScrollbarThumb = "HorizontalMinMaxScrollbarThumb";
        public const string hostview = "hostview";
        public const string IconButton = "IconButton";
        public const string INBigTitle = "IN BigTitle";
        public const string INBigTitleInner = "IN BigTitle Inner";
        public const string INColorField = "IN ColorField";
        public const string INDropDown = "IN DropDown";
        public const string INFoldout = "IN Foldout";
        public const string INFoldoutStatic = "IN FoldoutStatic";
        public const string INGameObjectHeader = "IN GameObjectHeader";
        public const string INLabel = "IN Label";
        public const string INLockButton = "IN LockButton";
        public const string INObjectField = "IN ObjectField";
        public const string INPopup = "IN Popup";
        public const string INRenderLayer = "IN RenderLayer";
        public const string INSelectedLine = "IN SelectedLine";
        public const string INTextField = "IN TextField";
        public const string INThumbnailSelection = "IN ThumbnailSelection";
        public const string INThumbnailShadow = "IN ThumbnailShadow";
        public const string INTitle = "IN Title";
        public const string INTitleText = "IN TitleText";
        public const string INToggle = "IN Toggle";
        public const string InnerShadowBg = "InnerShadowBg";
        public const string InsertionMarker = "InsertionMarker";
        public const string InvisibleButton = "InvisibleButton";
        public const string LargeButton = "LargeButton";
        public const string LargeButtonLeft = "LargeButtonLeft";
        public const string LargeButtonMid = "LargeButtonMid";
        public const string LargeButtonRight = "LargeButtonRight";
        public const string LargeDropDown = "LargeDropDown";
        public const string LargeLabel = "LargeLabel";
        public const string LargePopup = "LargePopup";
        public const string LargeTextField = "LargeTextField";
        public const string LightmapEditorSelectedHighlight = "LightmapEditorSelectedHighlight";
        public const string ListToggle = "ListToggle";
        public const string LockedHeaderBackground = "LockedHeaderBackground";
        public const string LockedHeaderButton = "LockedHeaderButton";
        public const string LockedHeaderLabel = "LockedHeaderLabel";
        public const string LODBlackBox = "LODBlackBox";
        public const string LODCameraLine = "LODCameraLine";
        public const string LODLevelNotifyText = "LODLevelNotifyText";
        public const string LODRendererAddButton = "LODRendererAddButton";
        public const string LODRendererButton = "LODRendererButton";
        public const string LODRendererRemove = "LODRendererRemove";
        public const string LODRenderersText = "LODRenderersText";
        public const string LODSceneText = "LODSceneText";
        public const string LODSliderBG = "LODSliderBG";
        public const string LODSliderRange = "LODSliderRange";
        public const string LODSliderRangeSelected = "LODSliderRangeSelected";
        public const string LODSliderText = "LODSliderText";
        public const string LODSliderTextSelected = "LODSliderTextSelected";
        public const string MeBlendBackground = "MeBlendBackground";
        public const string MeBlendPosition = "MeBlendPosition";
        public const string MeBlendTriangleLeft = "MeBlendTriangleLeft";
        public const string MeBlendTriangleRight = "MeBlendTriangleRight";
        public const string MeLivePlayBackground = "MeLivePlayBackground";
        public const string MeLivePlayBar = "MeLivePlayBar";
        public const string MenuItem = "MenuItem";
        public const string MenuItemMixed = "MenuItemMixed";
        public const string MeTimeLabel = "MeTimeLabel";
        public const string MeTransBGOver = "MeTransBGOver";
        public const string MeTransitionBack = "MeTransitionBack";
        public const string MeTransitionBlock = "MeTransitionBlock";
        public const string MeTransitionHandleLeft = "MeTransitionHandleLeft";
        public const string MeTransitionHandleLeftPrev = "MeTransitionHandleLeftPrev";
        public const string MeTransitionHandleRight = "MeTransitionHandleRight";
        public const string MeTransitionHead = "MeTransitionHead";
        public const string MeTransitionSelect = "MeTransitionSelect";
        public const string MeTransitionSelectHead = "MeTransitionSelectHead";
        public const string MeTransOff2On = "MeTransOff2On";
        public const string MeTransOffLeft = "MeTransOffLeft";
        public const string MeTransOffRight = "MeTransOffRight";
        public const string MeTransOn2Off = "MeTransOn2Off";
        public const string MeTransOnLeft = "MeTransOnLeft";
        public const string MeTransOnRight = "MeTransOnRight";
        public const string MeTransPlayhead = "MeTransPlayhead";
        public const string MiniBoldLabel = "MiniBoldLabel";
        public const string minibutton = "minibutton";
        public const string minibuttonleft = "minibuttonleft";
        public const string minibuttonmid = "minibuttonmid";
        public const string minibuttonright = "minibuttonright";
        public const string MiniLabel = "MiniLabel";
        public const string MiniLabelRight = "MiniLabelRight";
        public const string MiniMinMaxSliderHorizontal = "MiniMinMaxSliderHorizontal";
        public const string MiniMinMaxSliderVertical = "MiniMinMaxSliderVertical";
        public const string MiniPopup = "MiniPopup";
        public const string MiniPullDown = "MiniPullDown";
        public const string MiniPullDownLeft = "MiniPullDownLeft";
        public const string MiniSliderHorizontal = "MiniSliderHorizontal";
        public const string MiniSliderVertical = "MiniSliderVertical";
        public const string MiniTextField = "MiniTextField";
        public const string MiniToolbarButton = "MiniToolbarButton";
        public const string MiniToolbarButtonLeft = "MiniToolbarButtonLeft";
        public const string MiniToolbarPopup = "MiniToolbarPopup";
        public const string MinMaxHorizontalSliderThumb = "MinMaxHorizontalSliderThumb";
        public const string MuteToggle = "MuteToggle";
        public const string NotificationBackground = "NotificationBackground";
        public const string NotificationText = "NotificationText";
        public const string ObjectField = "ObjectField";
        public const string ObjectFieldMiniThumb = "ObjectFieldMiniThumb";
        public const string ObjectFieldThumb = "ObjectFieldThumb";
        public const string ObjectFieldThumbOverlay = "ObjectFieldThumbOverlay";
        public const string ObjectFieldThumbOverlay2 = "ObjectFieldThumbOverlay2";
        public const string ObjectPickerBackground = "ObjectPickerBackground";
        public const string ObjectPickerGroupHeader = "ObjectPickerGroupHeader";
        public const string ObjectPickerLargeStatus = "ObjectPickerLargeStatus";
        public const string ObjectPickerPreviewBackground = "ObjectPickerPreviewBackground";
        public const string ObjectPickerResultsEven = "ObjectPickerResultsEven";
        public const string ObjectPickerResultsGrid = "ObjectPickerResultsGrid";
        public const string ObjectPickerResultsGridLabel = "ObjectPickerResultsGridLabel";
        public const string ObjectPickerResultsOdd = "ObjectPickerResultsOdd";
        public const string ObjectPickerSmallStatus = "ObjectPickerSmallStatus";
        public const string ObjectPickerTab = "ObjectPickerTab";
        public const string ObjectPickerToolbar = "ObjectPickerToolbar";
        public const string OLbox = "OL box";
        public const string OLboxNoExpand = "OL box NoExpand";
        public const string OLElem = "OL Elem";
        public const string OLEntryBackEven = "OL EntryBackEven";
        public const string OLEntryBackOdd = "OL EntryBackOdd";
        public const string OLheader = "OL header";
        public const string OLLabel = "OL Label";
        public const string OLMinus = "OL Minus";
        public const string OLPlus = "OL Plus";
        public const string OLSelectedRow = "OL SelectedRow";
        public const string OLTextField = "OL TextField";
        public const string OLTitle = "OL Title";
        public const string OLTitleTextRight = "OL Title TextRight";
        public const string OLTitleleft = "OL Titleleft";
        public const string OLTitlemid = "OL Titlemid";
        public const string OLTitleright = "OL Titleright";
        public const string OLToggle = "OL Toggle";
        public const string OLToggleWhite = "OL ToggleWhite";
        public const string PaneOptions = "PaneOptions";
        public const string PlayerSettingsLevel = "PlayerSettingsLevel";
        public const string PlayerSettingsPlatform = "PlayerSettingsPlatform";
        public const string Popup = "Popup";
        public const string PopupBackground = "PopupBackground";
        public const string PopupCurveDropdown = "PopupCurveDropdown";
        public const string PopupCurveEditorBackground = "PopupCurveEditorBackground";
        public const string PopupCurveEditorSwatch = "PopupCurveEditorSwatch";
        public const string PopupCurveSwatchBackground = "PopupCurveSwatchBackground";
        public const string PRBrokenPrefabLabel = "PR BrokenPrefabLabel";
        public const string PRDigDownArrow = "PR DigDownArrow";
        public const string PRDisabledBrokenPrefabLabel = "PR DisabledBrokenPrefabLabel";
        public const string PRDisabledLabel = "PR DisabledLabel";
        public const string PRDisabledPrefabLabel = "PR DisabledPrefabLabel";
        public const string PRInsertion = "PR Insertion";
        public const string PRInsertionAbove = "PR Insertion Above";
        public const string PRLabel = "PR Label";
        public const string PRPing = "PR Ping";
        public const string PRPrefabLabel = "PR PrefabLabel";
        public const string PRTextField = "PR TextField";
        public const string PreBackground = "PreBackground";
        public const string PreButton = "PreButton";
        public const string PreDropDown = "PreDropDown";
        public const string PreferencesKeysElement = "PreferencesKeysElement";
        public const string PreferencesSection = "PreferencesSection";
        public const string PreferencesSectionBox = "PreferencesSectionBox";
        public const string PreHorizontalScrollbar = "PreHorizontalScrollbar";
        public const string PreHorizontalScrollbarThumb = "PreHorizontalScrollbarThumb";
        public const string PreLabel = "PreLabel";
        public const string PreOverlayLabel = "PreOverlayLabel";
        public const string PreSlider = "PreSlider";
        public const string PreSliderThumb = "PreSliderThumb";
        public const string PreToolbar = "PreToolbar";
        public const string PreToolbar2 = "PreToolbar2";
        public const string PreVerticalScrollbar = "PreVerticalScrollbar";
        public const string PreVerticalScrollbarThumb = "PreVerticalScrollbarThumb";
        public const string ProfilerBadge = "ProfilerBadge";
        public const string ProfilerLeftPane = "ProfilerLeftPane";
        public const string ProfilerLeftPaneOverlay = "ProfilerLeftPaneOverlay";
        public const string ProfilerPaneLeftBackground = "ProfilerPaneLeftBackground";
        public const string ProfilerPaneSubLabel = "ProfilerPaneSubLabel";
        public const string ProfilerRightPane = "ProfilerRightPane";
        public const string ProfilerScrollviewBackground = "ProfilerScrollviewBackground";
        public const string ProfilerSelectedLabel = "ProfilerSelectedLabel";
        public const string ProfilerTimelineBar = "ProfilerTimelineBar";
        public const string ProfilerTimelineFoldout = "ProfilerTimelineFoldout";
        public const string ProfilerTimelineLeftPane = "ProfilerTimelineLeftPane";
        public const string ProgressBarBack = "ProgressBarBack";
        public const string ProgressBarBar = "ProgressBarBar";
        public const string ProgressBarText = "ProgressBarText";
        public const string ProjectBrowserBottomBarBg = "ProjectBrowserBottomBarBg";
        public const string ProjectBrowserGridLabel = "ProjectBrowserGridLabel";
        public const string ProjectBrowserHeaderBgMiddle = "ProjectBrowserHeaderBgMiddle";
        public const string ProjectBrowserHeaderBgTop = "ProjectBrowserHeaderBgTop";
        public const string ProjectBrowserIconAreaBg = "ProjectBrowserIconAreaBg";
        public const string ProjectBrowserIconDropShadow = "ProjectBrowserIconDropShadow";
        public const string ProjectBrowserPreviewBg = "ProjectBrowserPreviewBg";
        public const string ProjectBrowserSubAssetBg = "ProjectBrowserSubAssetBg";
        public const string ProjectBrowserSubAssetBgCloseEnded = "ProjectBrowserSubAssetBgCloseEnded";
        public const string ProjectBrowserSubAssetBgDivider = "ProjectBrowserSubAssetBgDivider";
        public const string ProjectBrowserSubAssetBgMiddle = "ProjectBrowserSubAssetBgMiddle";
        public const string ProjectBrowserSubAssetBgOpenEnded = "ProjectBrowserSubAssetBgOpenEnded";
        public const string ProjectBrowserSubAssetExpandBtn = "ProjectBrowserSubAssetExpandBtn";
        public const string ProjectBrowserTextureIconDropShadow = "ProjectBrowserTextureIconDropShadow";
        public const string ProjectBrowserTopBarBg = "ProjectBrowserTopBarBg";
        public const string QualitySettingsDefault = "QualitySettingsDefault";
        public const string Radio = "Radio";
        public const string RectangleToolHBar = "RectangleToolHBar";
        public const string RectangleToolHBarLeft = "RectangleToolHBarLeft";
        public const string RectangleToolHBarRight = "RectangleToolHBarRight";
        public const string RectangleToolHighlight = "RectangleToolHighlight";
        public const string RectangleToolScaleBottom = "RectangleToolScaleBottom";
        public const string RectangleToolScaleLeft = "RectangleToolScaleLeft";
        public const string RectangleToolScaleRight = "RectangleToolScaleRight";
        public const string RectangleToolScaleTop = "RectangleToolScaleTop";
        public const string RectangleToolSelection = "RectangleToolSelection";
        public const string RectangleToolVBar = "RectangleToolVBar";
        public const string RectangleToolVBarBottom = "RectangleToolVBarBottom";
        public const string RectangleToolVBarTop = "RectangleToolVBarTop";
        public const string RegionBg = "RegionBg";
        public const string RightLabel = "RightLabel";
        public const string RLBackground = "RL Background";
        public const string RLDragHandle = "RL DragHandle";
        public const string RLElement = "RL Element";
        public const string RLFooter = "RL Footer";
        public const string RLFooterButton = "RL FooterButton";
        public const string RLHeader = "RL Header";
        public const string SCViewAxisLabel = "SC ViewAxisLabel";
        public const string SCViewLabel = "SC ViewLabel";
        public const string SceneViewOverlayTransparentBackground = "SceneViewOverlayTransparentBackground";
        public const string ScriptText = "ScriptText";
        public const string SearchCancelButton = "SearchCancelButton";
        public const string SearchCancelButtonEmpty = "SearchCancelButtonEmpty";
        public const string SearchModeFilter = "SearchModeFilter";
        public const string SearchTextField = "SearchTextField";
        public const string SelectionRect = "SelectionRect";
        public const string sequenceClip = "sequenceClip";
        public const string sequenceGroupFont = "sequenceGroupFont";
        public const string sequenceTrackHeaderFont = "sequenceTrackHeaderFont";
        public const string ShurikenCheckMark = "ShurikenCheckMark";
        public const string ShurikenCheckMarkMixed = "ShurikenCheckMarkMixed";
        public const string ShurikenDropdown = "ShurikenDropdown";
        public const string ShurikenEditableLabel = "ShurikenEditableLabel";
        public const string ShurikenEffectBg = "ShurikenEffectBg";
        public const string ShurikenEmitterTitle = "ShurikenEmitterTitle";
        public const string ShurikenLabel = "ShurikenLabel";
        public const string ShurikenMinus = "ShurikenMinus";
        public const string ShurikenModuleBg = "ShurikenModuleBg";
        public const string ShurikenModuleTitle = "ShurikenModuleTitle";
        public const string ShurikenObjectField = "ShurikenObjectField";
        public const string ShurikenPlus = "ShurikenPlus";
        public const string ShurikenPopup = "ShurikenPopup";
        public const string ShurikenToggle = "ShurikenToggle";
        public const string ShurikenToggleMixed = "ShurikenToggleMixed";
        public const string ShurikenValue = "ShurikenValue";
        public const string SimplePopup = "SimplePopup";
        public const string SliderMixed = "SliderMixed";
        public const string SoloToggle = "SoloToggle";
        public const string StaticDropdown = "StaticDropdown";
        public const string sv_iconselector_back = "sv_iconselector_back";
        public const string sv_iconselector_button = "sv_iconselector_button";
        public const string sv_iconselector_labelselection = "sv_iconselector_labelselection";
        public const string sv_iconselector_selection = "sv_iconselector_selection";
        public const string sv_iconselector_sep = "sv_iconselector_sep";
        public const string sv_label_0 = "sv_label_0";
        public const string sv_label_1 = "sv_label_1";
        public const string sv_label_2 = "sv_label_2";
        public const string sv_label_3 = "sv_label_3";
        public const string sv_label_4 = "sv_label_4";
        public const string sv_label_5 = "sv_label_5";
        public const string sv_label_6 = "sv_label_6";
        public const string sv_label_7 = "sv_label_7";
        public const string TabWindowBackground = "TabWindowBackground";
        public const string TagMenuItem = "Tag MenuItem";
        public const string TagTextField = "Tag TextField";
        public const string TagTextFieldButton = "Tag TextField Button";
        public const string TagTextFieldEmpty = "Tag TextField Empty";
        public const string TENodeBackground = "TE NodeBackground";
        public const string TENodeBox = "TE NodeBox";
        public const string TENodeBoxSelected = "TE NodeBoxSelected";
        public const string TENodeLabelBot = "TE NodeLabelBot";
        public const string TENodeLabelTop = "TE NodeLabelTop";
        public const string TEPinLabel = "TE PinLabel";
        public const string TEToolbar = "TE Toolbar";
        public const string TEtoolbarbutton = "TE toolbarbutton";
        public const string TEToolbarDropDown = "TE ToolbarDropDown";
        public const string TextFieldDropDown = "TextFieldDropDown";
        public const string TextFieldDropDownText = "TextFieldDropDownText";
        public const string TimeScrubber = "TimeScrubber";
        public const string TimeScrubberButton = "TimeScrubberButton";
        public const string tinyFont = "tinyFont";
        public const string TLBaseStateLogicBarOverlay = "TL BaseStateLogicBarOverlay";
        public const string TLEndPoint = "TL EndPoint";
        public const string TLInPoint = "TL InPoint";
        public const string TLItemTitle = "TL ItemTitle";
        public const string TLLeftColumn = "TL LeftColumn";
        public const string TLLeftItem = "TL LeftItem";
        public const string TLLogicBar0 = "TL LogicBar 0";
        public const string TLLogicBar1 = "TL LogicBar 1";
        public const string TLLogicBarparentgrey = "TL LogicBar parentgrey";
        public const string TLLoopSection = "TL LoopSection";
        public const string TLOutPoint = "TL OutPoint";
        public const string TLPlayhead = "TL Playhead";
        public const string TLRangeOverlay = "TL Range Overlay";
        public const string TLRightLine = "TL RightLine";
        public const string TLSelectionH1 = "TL Selection H1";
        public const string TLSelectionH2 = "TL Selection H2";
        public const string TLSelectionBarCloseButton = "TL SelectionBarCloseButton";
        public const string TLSelectionBarPreview = "TL SelectionBarPreview";
        public const string TLSelectionBarText = "TL SelectionBarText";
        public const string TLSelectionButton = "TL SelectionButton";
        public const string TLSelectionButtonPreDropGlow = "TL SelectionButton PreDropGlow";
        public const string TLSelectionButtonName = "TL SelectionButtonName";
        public const string TLSelectionButtonNew = "TL SelectionButtonNew";
        public const string TLtableft = "TL tab left";
        public const string TLtabmid = "TL tab mid";
        public const string TLtabplusleft = "TL tab plus left";
        public const string TLtabplusright = "TL tab plus right";
        public const string TLtabright = "TL tab right";
        public const string ToggleMixed = "ToggleMixed";
        public const string Toolbar = "Toolbar";
        public const string toolbarbutton = "toolbarbutton";
        public const string ToolbarDropDown = "ToolbarDropDown";
        public const string ToolbarPopup = "ToolbarPopup";
        public const string ToolbarSeachCancelButton = "ToolbarSeachCancelButton";
        public const string ToolbarSeachCancelButtonEmpty = "ToolbarSeachCancelButtonEmpty";
        public const string ToolbarSeachTextField = "ToolbarSeachTextField";
        public const string ToolbarSeachTextFieldPopup = "ToolbarSeachTextFieldPopup";
        public const string ToolbarSearchField = "ToolbarSearchField";
        public const string ToolbarTextField = "ToolbarTextField";
        public const string Tooltip = "Tooltip";
        public const string VCS_StickyNote = "VCS_StickyNote";
        public const string VCS_StickyNoteArrow = "VCS_StickyNoteArrow";
        public const string VCS_StickyNoteLabel = "VCS_StickyNoteLabel";
        public const string VCS_StickyNoteP4 = "VCS_StickyNoteP4";
        public const string VerticalMinMaxScrollbarThumb = "VerticalMinMaxScrollbarThumb";
        public const string VisibilityToggle = "VisibilityToggle";
        public const string WarningOverlay = "WarningOverlay";
        public const string WhiteBoldLabel = "WhiteBoldLabel";
        public const string WhiteLabel = "WhiteLabel";
        public const string WhiteLargeLabel = "WhiteLargeLabel";
        public const string WhiteMiniLabel = "WhiteMiniLabel";
        public const string WinBtnClose = "WinBtnClose";
        public const string WinBtnCloseActiveMac = "WinBtnCloseActiveMac";
        public const string WinBtnCloseMac = "WinBtnCloseMac";
        public const string WinBtnInactiveMac = "WinBtnInactiveMac";
        public const string WinBtnMax = "WinBtnMax";
        public const string WinBtnMaxActiveMac = "WinBtnMaxActiveMac";
        public const string WinBtnMaxMac = "WinBtnMaxMac";
        public const string WinBtnMin = "WinBtnMin";
        public const string WinBtnMinActiveMac = "WinBtnMinActiveMac";
        public const string WinBtnMinMac = "WinBtnMinMac";
        public const string WindowBackground = "WindowBackground";
        public const string WindowBottomResize = "WindowBottomResize";
        public const string WizardBox = "Wizard Box";
        public const string WizardError = "Wizard Error";
        public const string WordWrapLabel = "WordWrapLabel";
        public const string WordWrappedLabel = "WordWrappedLabel";
        public const string WordWrappedMiniLabel = "WordWrappedMiniLabel";
        public const string WrappedLabel = "WrappedLabel";
    }

    public static class GUIIcons {
        public static Texture GetIcon(string key) {
            return EditorGUIUtility.IconContent(key).image;
        }

        public static Texture FindUnityIcon(this Type type, string defaultIcon = dll_Script_Icon) {
            var tex = EditorGUIUtility.ObjectContent(null, type).image;
            if (tex == null) {
                tex = EditorGUIUtility.IconContent(defaultIcon).image;
            }

            return tex;
        }

        public const string ScriptableObject_Icon = "ScriptableObject Icon";
        public const string Clipboard = "Clipboard";
        public const string SocialNetworks_UDNOpen = "SocialNetworks.UDNOpen";
        public const string SocialNetworks_Tweet = "SocialNetworks.Tweet";
        public const string SocialNetworks_FacebookShare = "SocialNetworks.FacebookShare";
        public const string SocialNetworks_LinkedInShare = "SocialNetworks.LinkedInShare";
        public const string SocialNetworks_UDNLogo = "SocialNetworks.UDNLogo";
        public const string animationvisibilitytoggleoff = "animationvisibilitytoggleoff";
        public const string animationvisibilitytoggleon = "animationvisibilitytoggleon";
        public const string tree_icon = "tree_icon";
        public const string tree_icon_leaf = "tree_icon_leaf";
        public const string tree_icon_frond = "tree_icon_frond";
        public const string tree_icon_branch = "tree_icon_branch";
        public const string tree_icon_branch_frond = "tree_icon_branch_frond";
        public const string editicon_sml = "editicon.sml";
        public const string TreeEditor_Refresh = "TreeEditor.Refresh";
        public const string TreeEditor_Duplicate = "TreeEditor.Duplicate";
        public const string TreeEditor_Trash = "TreeEditor.Trash";
        public const string TreeEditor_AddBranches = "TreeEditor.AddBranches";
        public const string TreeEditor_AddLeaves = "TreeEditor.AddLeaves";
        public const string RightFingersIk = "RightFingersIk";
        public const string LeftFingersIk = "LeftFingersIk";
        public const string RightFeetIk = "RightFeetIk";
        public const string LeftFeetIk = "LeftFeetIk";
        public const string MaskEditor_Root = "MaskEditor_Root";
        public const string BodyPartPicker = "BodyPartPicker";
        public const string BodySIlhouette = "BodySIlhouette";
        public const string Mirror = "Mirror";
        public const string Toolbar_Minus = "Toolbar Minus";
        public const string Toolbar_Plus_More = "Toolbar Plus More";
        public const string Toolbar_Plus = "Toolbar Plus";
        public const string AnimatorController_Icon = "AnimatorController Icon";
        public const string TextAsset_Icon = "TextAsset Icon";
        public const string Shader_Icon = "Shader Icon";
        public const string boo_Script_Icon = "boo Script Icon";
        public const string dll_Script_Icon = "dll Script Icon";
        public const string cs_Script_Icon = "cs Script Icon";
        public const string js_Script_Icon = "js Script Icon";
        public const string Prefab_Icon = "Prefab Icon";
        public const string Profiler_NextFrame = "Profiler.NextFrame";
        public const string Profiler_PrevFrame = "Profiler.PrevFrame";
        public const string ColorPicker_CycleSlider = "ColorPicker.CycleSlider";
        public const string ColorPicker_CycleColor = "ColorPicker.CycleColor";
        public const string EyeDropper_Large = "EyeDropper.Large";
        public const string ClothInspector_PaintValue = "ClothInspector.PaintValue";
        public const string ClothInspector_ViewValue = "ClothInspector.ViewValue";
        public const string ClothInspector_SettingsTool = "ClothInspector.SettingsTool";
        public const string ClothInspector_PaintTool = "ClothInspector.PaintTool";
        public const string ClothInspector_SelectTool = "ClothInspector.SelectTool";
        public const string WelcomeScreen_AssetStoreLogo = "WelcomeScreen.AssetStoreLogo";
        public const string AboutWindow_MainHeader = "AboutWindow.MainHeader";
        public const string AgeiaLogo = "AgeiaLogo";
        public const string MonoLogo = "MonoLogo";
        public const string PlayButtonProfile_Anim = "PlayButtonProfile Anim";
        public const string StepButton_Anim = "StepButton Anim";
        public const string PauseButton_Anim = "PauseButton Anim";
        public const string PlayButton_Anim = "PlayButton Anim";
        public const string PlayButtonProfile_On = "PlayButtonProfile On";
        public const string StepButton_On = "StepButton On";
        public const string PauseButton_On = "PauseButton On";
        public const string PlayButton_On = "PlayButton On";
        public const string PlayButtonProfile = "PlayButtonProfile";
        public const string StepButton = "StepButton";
        public const string ViewToolOrbit_On = "ViewToolOrbit On";
        public const string ViewToolZoom_On = "ViewToolZoom On";
        public const string ViewToolMove_On = "ViewToolMove On";
        public const string ViewToolZoom = "ViewToolZoom";
        public const string ViewToolMove = "ViewToolMove";
        public const string ViewToolOrbit = "ViewToolOrbit";
        public const string ScaleTool_On = "ScaleTool On";
        public const string RotateTool_On = "RotateTool On";
        public const string MoveTool_On = "MoveTool On";
        public const string ScaleTool = "ScaleTool";
        public const string RotateTool = "RotateTool";
        public const string MoveTool = "MoveTool";
        public const string _Help = "_Help";
        public const string _Popup = "_Popup";
        public const string Icon_Dropdown = "Icon Dropdown";
        public const string Avatar_Icon = "Avatar Icon";
        public const string AvatarPivot = "AvatarPivot";
        public const string SpeedScale = "SpeedScale";
        public const string DotSelection = "DotSelection";
        public const string DotFrameDotted = "DotFrameDotted";
        public const string DotFrame = "DotFrame";
        public const string DotFill = "DotFill";
        public const string RightHandZoom = "RightHandZoom";
        public const string LeftHandZoom = "LeftHandZoom";
        public const string HeadZoom = "HeadZoom";
        public const string RightLeg = "RightLeg";
        public const string LeftLeg = "LeftLeg";
        public const string RightFingers = "RightFingers";
        public const string RightArm = "RightArm";
        public const string LeftFingers = "LeftFingers";
        public const string LeftArm = "LeftArm";
        public const string Head = "Head";
        public const string Torso = "Torso";
        public const string RightHandZoomSilhouette = "RightHandZoomSilhouette";
        public const string LeftHandZoomSilhouette = "LeftHandZoomSilhouette";
        public const string HeadZoomSilhouette = "HeadZoomSilhouette";
        public const string AvatarInspector = "AvatarInspector";
        public const string BodySilhouette = "BodySilhouette";
        public const string Animation_AddKeyframe = "Animation.AddKeyframe";
        public const string Animation_NextKey = "Animation.NextKey";
        public const string Animation_PrevKey = "Animation.PrevKey";
        public const string redLight = "redLight";
        public const string orangeLight = "orangeLight";
        public const string lightRim = "lightRim";
        public const string greenLight = "greenLight";
        public const string Animation_AddEvent = "Animation.AddEvent";
        public const string SceneviewAudio = "SceneviewAudio";
        public const string SceneviewLighting = "SceneviewLighting";
        public const string MeshRenderer_Icon = "MeshRenderer Icon";
        public const string Terrain_Icon = "Terrain Icon";
        public const string BuildSettings_SelectedIcon = "BuildSettings.SelectedIcon";
        public const string Animation_Record = "Animation.Record";
        public const string Animation_Play = "Animation.Play";
        public const string TerrainInspector_TerrainToolSettings = "TerrainInspector.TerrainToolSettings";
        public const string TerrainInspector_TerrainToolPlants = "TerrainInspector.TerrainToolPlants";
        public const string TerrainInspector_TerrainToolTrees = "TerrainInspector.TerrainToolTrees";
        public const string TerrainInspector_TerrainToolSplat = "TerrainInspector.TerrainToolSplat";
        public const string TerrainInspector_TerrainToolSmoothHeight = "TerrainInspector.TerrainToolSmoothHeight";
        public const string TerrainInspector_TerrainToolSetHeight = "TerrainInspector.TerrainToolSetHeight";
        public const string TerrainInspector_TerrainToolRaise = "TerrainInspector.TerrainToolRaise";
        public const string SettingsIcon = "SettingsIcon";
        public const string PauseButton = "PauseButton";
        public const string PlayButton = "PlayButton";
        public const string Camera_Icon = "Camera Icon";
        public const string Animation_EventMarker = "Animation.EventMarker";
        public const string AS_Badge_New = "AS Badge New";
        public const string AS_Badge_Move = "AS Badge Move";
        public const string AS_Badge_Delete = "AS Badge Delete";
        public const string WaitSpin00 = "WaitSpin00";
        public const string WaitSpin01 = "WaitSpin01";
        public const string WaitSpin02 = "WaitSpin02";
        public const string WaitSpin03 = "WaitSpin03";
        public const string WaitSpin04 = "WaitSpin04";
        public const string WaitSpin05 = "WaitSpin05";
        public const string WaitSpin06 = "WaitSpin06";
        public const string WaitSpin07 = "WaitSpin07";
        public const string WaitSpin08 = "WaitSpin08";
        public const string WaitSpin09 = "WaitSpin09";
        public const string WaitSpin10 = "WaitSpin10";
        public const string WaitSpin11 = "WaitSpin11";
        public const string WelcomeScreen_UnityAnswersLogo = "WelcomeScreen.UnityAnswersLogo";
        public const string WelcomeScreen_UnityForumLogo = "WelcomeScreen.UnityForumLogo";
        public const string WelcomeScreen_UnityBasicsLogo = "WelcomeScreen.UnityBasicsLogo";
        public const string WelcomeScreen_VideoTutLogo = "WelcomeScreen.VideoTutLogo";
        public const string WelcomeScreen_MainHeader = "WelcomeScreen.MainHeader";
        public const string UnityLogo = "UnityLogo";
        public const string PreMatLight1 = "PreMatLight1";
        public const string PreMatLight0 = "PreMatLight0";
        public const string PreMatTorus = "PreMatTorus";
        public const string PreMatCylinder = "PreMatCylinder";
        public const string PreMatCube = "PreMatCube";
        public const string PreMatSphere = "PreMatSphere";
        public const string PreTextureMipMapHigh = "PreTextureMipMapHigh";
        public const string PreTextureMipMapLow = "PreTextureMipMapLow";
        public const string PreTextureRGB = "PreTextureRGB";
        public const string PreTextureAlpha = "PreTextureAlpha";
        public const string VerticalSplit = "VerticalSplit";
        public const string HorizontalSplit = "HorizontalSplit";
        public const string PrefabNormal_Icon = "PrefabNormal Icon";
        public const string PrefabModel_Icon = "PrefabModel Icon";
        public const string GameObject_Icon = "GameObject Icon";
        public const string preAudioLoopOn = "preAudioLoopOn";
        public const string preAudioLoopOff = "preAudioLoopOff";
        public const string preAudioPlayOn = "preAudioPlayOn";
        public const string preAudioPlayOff = "preAudioPlayOff";
        public const string preAudioAutoPlayOn = "preAudioAutoPlayOn";
        public const string preAudioAutoPlayOff = "preAudioAutoPlayOff";
        public const string BuildSettings_Web_Small = "BuildSettings.Web.Small";
        public const string BuildSettings_Standalone_Small = "BuildSettings.Standalone.Small";
        public const string BuildSettings_iPhone_Small = "BuildSettings.iPhone.Small";
        public const string BuildSettings_Android_Small = "BuildSettings.Android.Small";
        public const string BuildSettings_BlackBerry_Small = "BuildSettings.BlackBerry.Small";
        public const string BuildSettings_Tizen_Small = "BuildSettings.Tizen.Small";
        public const string BuildSettings_XBox360_Small = "BuildSettings.XBox360.Small";
        public const string BuildSettings_XboxOne_Small = "BuildSettings.XboxOne.Small";
        public const string BuildSettings_PS3_Small = "BuildSettings.PS3.Small";
        public const string BuildSettings_PSP2_Small = "BuildSettings.PSP2.Small";
        public const string BuildSettings_PS4_Small = "BuildSettings.PS4.Small";
        public const string BuildSettings_PSM_Small = "BuildSettings.PSM.Small";
        public const string BuildSettings_FlashPlayer_Small = "BuildSettings.FlashPlayer.Small";
        public const string BuildSettings_Metro_Small = "BuildSettings.Metro.Small";
        public const string BuildSettings_WP8_Small = "BuildSettings.WP8.Small";
        public const string BuildSettings_SamsungTV_Small = "BuildSettings.SamsungTV.Small";
        public const string BuildSettings_Web = "BuildSettings.Web";
        public const string BuildSettings_Standalone = "BuildSettings.Standalone";
        public const string BuildSettings_iPhone = "BuildSettings.iPhone";
        public const string BuildSettings_Android = "BuildSettings.Android";
        public const string BuildSettings_BlackBerry = "BuildSettings.BlackBerry";
        public const string BuildSettings_Tizen = "BuildSettings.Tizen";
        public const string BuildSettings_XBox360 = "BuildSettings.XBox360";
        public const string BuildSettings_XboxOne = "BuildSettings.XboxOne";
        public const string BuildSettings_PS3 = "BuildSettings.PS3";
        public const string BuildSettings_PSP2 = "BuildSettings.PSP2";
        public const string BuildSettings_PS4 = "BuildSettings.PS4";
        public const string BuildSettings_PSM = "BuildSettings.PSM";
        public const string BuildSettings_FlashPlayer = "BuildSettings.FlashPlayer";
        public const string BuildSettings_Metro = "BuildSettings.Metro";
        public const string BuildSettings_WP8 = "BuildSettings.WP8";
        public const string BuildSettings_SamsungTV = "BuildSettings.SamsungTV";
        public const string TreeEditor_BranchTranslate = "TreeEditor.BranchTranslate";
        public const string TreeEditor_BranchRotate = "TreeEditor.BranchRotate";
        public const string TreeEditor_BranchFreeHand = "TreeEditor.BranchFreeHand";
        public const string TreeEditor_LeafTranslate_On = "TreeEditor.LeafTranslate On";
        public const string TreeEditor_LeafRotate_On = "TreeEditor.LeafRotate On";
        public const string sv_icon_dot15_pix16_gizmo = "sv_icon_dot15_pix16_gizmo";
        public const string sv_icon_dot1_sml = "sv_icon_dot1_sml";
        public const string sv_icon_dot4_sml = "sv_icon_dot4_sml";
        public const string sv_icon_dot7_sml = "sv_icon_dot7_sml";
        public const string sv_icon_dot5_pix16_gizmo = "sv_icon_dot5_pix16_gizmo";
        public const string sv_icon_dot11_pix16_gizmo = "sv_icon_dot11_pix16_gizmo";
        public const string sv_icon_dot12_sml = "sv_icon_dot12_sml";
        public const string sv_icon_dot15_sml = "sv_icon_dot15_sml";
        public const string sv_icon_dot9_pix16_gizmo = "sv_icon_dot9_pix16_gizmo";
        public const string sv_icon_name6 = "sv_icon_name6";
        public const string sv_icon_name3 = "sv_icon_name3";
        public const string sv_icon_name4 = "sv_icon_name4";
        public const string sv_icon_name0 = "sv_icon_name0";
        public const string sv_icon_name1 = "sv_icon_name1";
        public const string sv_icon_name2 = "sv_icon_name2";
        public const string sv_icon_name5 = "sv_icon_name5";
        public const string sv_icon_name7 = "sv_icon_name7";
        public const string sv_icon_dot1_pix16_gizmo = "sv_icon_dot1_pix16_gizmo";
        public const string sv_icon_dot8_pix16_gizmo = "sv_icon_dot8_pix16_gizmo";
        public const string sv_icon_dot2_pix16_gizmo = "sv_icon_dot2_pix16_gizmo";
        public const string sv_icon_dot6_pix16_gizmo = "sv_icon_dot6_pix16_gizmo";
        public const string sv_icon_dot0_sml = "sv_icon_dot0_sml";
        public const string sv_icon_dot3_sml = "sv_icon_dot3_sml";
        public const string sv_icon_dot6_sml = "sv_icon_dot6_sml";
        public const string sv_icon_dot9_sml = "sv_icon_dot9_sml";
        public const string sv_icon_dot11_sml = "sv_icon_dot11_sml";
        public const string sv_icon_dot14_sml = "sv_icon_dot14_sml";
        public const string sv_label_0 = "sv_label_0";
        public const string sv_label_1 = "sv_label_1";
        public const string sv_label_2 = "sv_label_2";
        public const string sv_label_3 = "sv_label_3";
        public const string sv_label_5 = "sv_label_5";
        public const string sv_label_6 = "sv_label_6";
        public const string sv_label_7 = "sv_label_7";
        public const string sv_icon_none = "sv_icon_none";
        public const string sv_icon_dot14_pix16_gizmo = "sv_icon_dot14_pix16_gizmo";
        public const string sv_icon_dot7_pix16_gizmo = "sv_icon_dot7_pix16_gizmo";
        public const string sv_icon_dot3_pix16_gizmo = "sv_icon_dot3_pix16_gizmo";
        public const string sv_icon_dot0_pix16_gizmo = "sv_icon_dot0_pix16_gizmo";
        public const string sv_icon_dot2_sml = "sv_icon_dot2_sml";
        public const string sv_icon_dot5_sml = "sv_icon_dot5_sml";
        public const string sv_icon_dot8_sml = "sv_icon_dot8_sml";
        public const string sv_icon_dot10_pix16_gizmo = "sv_icon_dot10_pix16_gizmo";
        public const string sv_icon_dot12_pix16_gizmo = "sv_icon_dot12_pix16_gizmo";
        public const string sv_icon_dot10_sml = "sv_icon_dot10_sml";
        public const string sv_icon_dot13_sml = "sv_icon_dot13_sml";
        public const string sv_icon_dot4_pix16_gizmo = "sv_icon_dot4_pix16_gizmo";
        public const string sv_label_4 = "sv_label_4";
        public const string sv_icon_dot13_pix16_gizmo = "sv_icon_dot13_pix16_gizmo";
    }

    public static class EditorX {
        public static void ForGizmo(Vector3 pos, Vector3 direction, float arrowHeadLength = 0.25f,
            float arrowHeadAngle = 20.0f, float arrowPosition = 0.5f) {
            ForGizmo(pos, direction, Gizmos.color, arrowHeadLength, arrowHeadAngle, arrowPosition);
        }

        public static void ForGizmo(Vector3 pos, Vector3 direction, Color color, float arrowHeadLength = 0.25f,
            float arrowHeadAngle = 20.0f, float arrowPosition = 0.5f) {
            Gizmos.color = color;
            Gizmos.DrawRay(pos, direction);
            DrawArrowEnd(true, pos, direction, color, arrowHeadLength, arrowHeadAngle, arrowPosition);
        }

        public static void ForDebug(Vector3 pos, Vector3 direction, float arrowHeadLength = 0.25f,
            float arrowHeadAngle = 20.0f, float arrowPosition = 0.5f) {
            ForDebug(pos, direction, Color.white, arrowHeadLength, arrowHeadAngle, arrowPosition);
        }

        public static void ForDebug(Vector3 pos, Vector3 direction, Color color, float arrowHeadLength = 0.25f,
            float arrowHeadAngle = 20.0f, float arrowPosition = 0.5f) {
            Debug.DrawRay(pos, direction, color);
            DrawArrowEnd(false, pos, direction, color, arrowHeadLength, arrowHeadAngle, arrowPosition);
        }

        private static void DrawArrowEnd(bool gizmos, Vector3 pos, Vector3 direction, Color color,
            float arrowHeadLength = 0.25f, float arrowHeadAngle = 20.0f, float arrowPosition = 0.5f) {
            var right =
                (Quaternion.LookRotation(direction) * Quaternion.Euler(arrowHeadAngle, 0, 0) * Vector3.back) *
                arrowHeadLength;
            var left =
                (Quaternion.LookRotation(direction) * Quaternion.Euler(-arrowHeadAngle, 0, 0) * Vector3.back) *
                arrowHeadLength;
            var up = (Quaternion.LookRotation(direction) * Quaternion.Euler(0, arrowHeadAngle, 0) * Vector3.back) *
                     arrowHeadLength;
            var down =
                (Quaternion.LookRotation(direction) * Quaternion.Euler(0, -arrowHeadAngle, 0) * Vector3.back) *
                arrowHeadLength;

            var arrowTip = pos + (direction * arrowPosition);

            if (gizmos) {
                Gizmos.color = color;
                Gizmos.DrawRay(arrowTip, right);
                Gizmos.DrawRay(arrowTip, left);
                Gizmos.DrawRay(arrowTip, up);
                Gizmos.DrawRay(arrowTip, down);
            }
            else {
                Debug.DrawRay(arrowTip, right, color);
                Debug.DrawRay(arrowTip, left, color);
                Debug.DrawRay(arrowTip, up, color);
                Debug.DrawRay(arrowTip, down, color);
            }
        }

        public static void ForHandles(Vector3 pos, Vector3 direction, Color color, float arrowHeadLength = 0.25f,
            float arrowHeadAngle = 20.0f, float arrowPosition = 1.0f) {
            Handles.color = color;
            Handles.DrawLine(pos, pos + direction);
            DrawArrowEndHandles(pos, direction, color, arrowHeadLength, arrowHeadAngle, arrowPosition);
        }

        private static void DrawArrowEndHandles(Vector3 pos, Vector3 direction, Color color,
            float arrowHeadLength = 0.25f, float arrowHeadAngle = 20.0f, float arrowPosition = 0.5f) {
            var right =
                (Quaternion.LookRotation(direction) * Quaternion.Euler(arrowHeadAngle, 0, 0) * Vector3.back) *
                arrowHeadLength;
            var left =
                (Quaternion.LookRotation(direction) * Quaternion.Euler(-arrowHeadAngle, 0, 0) * Vector3.back) *
                arrowHeadLength;
            var up = (Quaternion.LookRotation(direction) * Quaternion.Euler(0, arrowHeadAngle, 0) * Vector3.back) *
                     arrowHeadLength;
            var down =
                (Quaternion.LookRotation(direction) * Quaternion.Euler(0, -arrowHeadAngle, 0) * Vector3.back) *
                arrowHeadLength;

            var arrowTip = pos + direction * arrowPosition;


            Handles.DrawLine(arrowTip, right + arrowTip);
            Handles.DrawLine(arrowTip, left + arrowTip);
            Handles.DrawLine(arrowTip, up + arrowTip);
            Handles.DrawLine(arrowTip, down + arrowTip);
        }

        public static void DrawBoundaries(Vector2Int minCell, Vector2Int maxCell, Grid navmeshGrid) {
            var min = navmeshGrid.GetCellCenterWorld((Vector3Int) minCell);
            var max = navmeshGrid.GetCellCenterWorld((Vector3Int) maxCell);
            Handles.DrawDottedLines(
                new[] {
                    new Vector3(min.x, min.y),
                    new Vector3(min.x, max.y),
                    new Vector3(max.x, max.y),
                    new Vector3(max.x, min.y)
                },
                new[] {
                    0, 1,
                    1, 2,
                    2, 3,
                    3, 0
                },
                NavMesh2DEditor.kBoundariesWidth
            );
        }
    }
}